import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

export interface PersonaReview {
  persona: 'structural' | 'print' | 'cost' | 'aesthetics';
  persona_display: string;
  weight: number;
  score: number;
  verdict_et: string;
  findings: string[];
  suggestions: { label_et: string; rationale_et: string; param?: string; new_value?: number }[];
  error?: string;
}

export interface DfmIssue {
  severity: 'critical' | 'warning' | 'info';
  rule: string;
  message_et: string;
  affected_param?: string;
  suggested_value?: number;
}

export interface DfmReport {
  template: string;
  score: number;
  summary_et: string;
  counts: { critical: number; warning: number; info: number };
  issues: DfmIssue[];
}

export interface Synthesis {
  overall: 'ship_it' | 'iterate' | 'redesign';
  verdict_et: string;
  top_actions: {
    label_et: string;
    rationale_et: string;
    priority: number;
    param?: string;
    new_value?: number;
    backed_by?: string[];
  }[];
}

export interface CouncilResult {
  dfm?: DfmReport;
  agents: PersonaReview[];
  council_score: number;
  synthesis: Synthesis;
}

/** SSE event types generated by /api/ai/iterate */
export type IterateEvent =
  | { type: 'start'; target: number; initial_spec: any }
  | { type: 'review'; step: number; score: number; verdict_et: string; spec: any }
  | {
      type: 'patch';
      step: number;
      param: string;
      old: any;
      new: number;
      rationale_et: string;
      label_et: string;
    }
  | {
      type: 'stop';
      reason: 'target_reached' | 'max_iter' | 'no_improvement' | 'no_patch_available' | 'review_failed';
      final_score: number;
      final_spec: any;
      final_verdict_et?: string;
    }
  | { type: 'error'; step: number; message: string };

@Injectable({ providedIn: 'root' })
export class AiStudioService {
  private http = inject(HttpClient);
  private base = '/api/ai';

  council(spec: any, promptEt?: string, imageBase64?: string): Observable<CouncilResult> {
    return this.http.post<CouncilResult>(`${this.base}/review-council`, {
      spec,
      prompt_et: promptEt,
      image_base64: imageBase64,
    });
  }

  dfm(spec: any): Observable<DfmReport> {
    return this.http.post<DfmReport>(`${this.base}/dfm`, spec);
  }

  /**
   * Streaming generative loop. Tagastab AsyncIterable-tüüpi stream'i —
   * Angular-sõbralik viis näidata iga uut sündmust UI-s.
   */
  iterateStream(spec: any, promptEt?: string, targetScore?: number): ReadableStream<IterateEvent> {
    const body = JSON.stringify({ spec, prompt_et: promptEt, target_score: targetScore });

    return new ReadableStream<IterateEvent>({
      async start(controller) {
        try {
          const resp = await fetch('/api/ai/iterate', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body,
          });
          if (!resp.body) {
            controller.error(new Error('No response body'));
            return;
          }
          const reader = resp.body.getReader();
          const decoder = new TextDecoder();
          let buffer = '';
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            buffer += decoder.decode(value, { stream: true });
            // SSE puhul: sõnumid eraldatud topelttsõuga, `data:` read sisu
            let idx;
            while ((idx = buffer.indexOf('\n\n')) >= 0) {
              const raw = buffer.slice(0, idx);
              buffer = buffer.slice(idx + 2);
              const data = raw
                .split('\n')
                .filter((l) => l.startsWith('data:'))
                .map((l) => l.slice(5).trim())
                .join('');
              if (data) {
                try {
                  controller.enqueue(JSON.parse(data));
                } catch {
                  /* halvasti vormindatud */
                }
              }
            }
          }
          controller.close();
        } catch (err) {
          controller.error(err);
        }
      },
    });
  }
}
