; generated by PrusaSlicer 2.7.0 on 2026-04-17 at 12:05:00 UTC
; filament used [mm] = 81234.50
; filament used [cm3] = 195.21
; filament used [g] = 242.06
; filament cost = 6.05
; estimated printing time (normal mode) = 1d 3h 14m 22s
