; generated by PrusaSlicer 2.7.0 on 2026-04-17 at 18:42:11 UTC
;
; external perimeters extrusion width = 0.45mm (3.25mm^3/s)
; perimeters extrusion width = 0.45mm (8.67mm^3/s)
; infill extrusion width = 0.45mm (21.45mm^3/s)
; solid infill extrusion width = 0.45mm (6.67mm^3/s)
; top infill extrusion width = 0.40mm (5.33mm^3/s)
;
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; filament used [mm] = 2487.35
; filament used [cm3] = 5.98
; filament used [g] = 7.42
; filament cost = 0.19
; estimated printing time (normal mode) = 0h 23m 17s
; estimated printing time (silent mode) = 0h 26m 04s
; profile: pla_default
; filament_type = PLA
; filament_density = 1.24
; filament_diameter = 1.75
